# OpenVPN Container

# OS
FROM alpine:3.7

# labels
MAINTAINER B14ckP4nd4 <b14ckp4nd4@protonmail.com>

# Arguments
PORT=443
PROTOCOL='tcp'

# environments
ENV PORT=$PORT
ENV PROTOCOL=$PROTO
ENV DEBUG=1
ENV OPENVPN_PATH="/etc/openvpn"
ENV CONFIG_PATH="/config"
ENV EASYRSA /usr/share/easy-rsa
ENV INTERFACE="eth0"

# install dependencies

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories \
    #install Dependencies
    &&  apk add --no-cache --update openvpn iptables bash easy-rsa openvpn-auth-pam google-authenticator pamtester bash wget curl \
    # link easy-rsa to bin
    &&  ln -s /usr/share/easy-rsa/easyrsa /usr/local/bin


# start Service
CMD ["openvpn_init"]

VOLUME $CONFIG

ADD ./usr/local/bin /
RUN chmod a+x /usr/local/bin/*